# Generated by Django 4.2.6 on 2023-10-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user_id_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
