# Generated by Django 4.2.6 on 2023-10-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_post_id_like_post_rename_user_id_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
